# 합리적인 소비를 위한 시장 농수축산물 시장가격에 대한 분석

## 지역별,날씨별,계절별 데이터 분석

- 학번:2024105245

- 학과:소프트웨어 융합학과

- 학년:1

- 이름:김현정

# 목차
  1. 주제 선정 이유
  2. 가설 정의
  3. 분석할 데이터의 출처와 데이터 내용설명 
  4. 참고자료

# 1.주제 선정 이유
- 장을 볼 때마다 계속 달라지는 농수산물들의 가격들과 같은 서울이더라도 지역마다 다른 가격의 농수산물을 보고 치솟는 물가인 오늘날
최적의 합리적인 소비를 하기위해 시장(서울지역)에서 농수산물이 얼만큼 다양하게 어떻게 다른지 분석해보았다

# 2 가설 설정
1. 소득수준이 높은 동네일수록 농수산물 가격이 비싸다. 
2. 비가 오는 날씨일 때 농수산물이 더 싸다.
3. 수확의 계절 가을에 농수산물이 더 싸다.

# 3. 분석할 데이터의 출처와 데이터 내용설명

1. 서울시 생필품 농수축산물 가격 정보
- 제공기관: 서울특별시
- 데이터 등록 날짜: 2012.06.22.
- 데이터 최종 수정날짜: 2024.05.15.
- 설명: 서울시 물가모니터가 주1회 자치구별 전통시장에 나가 농수축산물 16개 품목을 조사하고 그 가격을 공개하는 정보입니다.
- 데이터 출처 링크: https://data.seoul.go.kr/dataList/OA-1170/S/1/datasetView.do
2. 서울시 자치구별 1인당 지역내총생산 및 수준지수(2015년 기준) 통계
- 제공기관: 서울특별시
- 데이터 등록 날짜: 2020.07.01.
- 데이터 최종 수정날짜: 2022.01.25.
- 설명: 서울시 자치구별 지역내총생산, 1인당 지역내총생산 현황을 제공하는 정보입니다.
- 데이터 출처 링크: https://data.seoul.go.kr/dataList/11063/S/2/datasetView.do
3. 서울시 날짜별 강수량
- 제공기관: 기상청
- 데이터 등록 날짜: 2022.1.1.
- 데이터 최종 수정날짜: 2024.05.15.
- 설명: 서울시 날짜별 강수량을 제공하는 정보입니다.
-  데이터 출처 링크:https://data.kma.go.kr/stcs/grnd/grndRnList.do?pgmNo=69#.

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel("./서울시 생필품 농수축산물 가격 정보.xlsx")
df2 = pd.read_excel("./서울시 날짜별 강수량.xlsx")#4일에 한 번씩 측정됨
df3 = pd.read_excel("./자치구별+1인당+지역내총생산+및+수준지수(2015년+기준)_20240516010808.xlsx")

In [3]:
df1

,일련번호,시장/마트 번호,시장/마트 이름,품목 번호,품목 이름,실판매규격,가격(원),년도-월,비고,점검일자,시장유형 구분(시장/마트) 코드,시장유형 구분(시장/마트) 이름,자치구 코드,자치구 이름
0,345108,90,우림시장,42,갈치 1마리,NaN,3500,2024-04-01 00:00:00,50cm 작음,2024-04-29 00:00:00,1,전통시장,260000,중랑구
1,345109,90,우림시장,19,감자 1kg,NaN,4500,2024-04-01 00:00:00,NaN,2024-04-29 00:00:00,1,전통시장,260000,중랑구
2,345110,90,우림시장,37,계란 10개,NaN,6650,2024-04-01 00:00:00,풀무원통통신선란,2024-04-29 00:00:00,1,전통시장,260000,중랑구
3,345111,90,우림시장,20,고구마 1kg,NaN,4500,2024-04-01 00:00:00,NaN,2024-04-29 00:00:00,1,전통시장,260000,중랑구
4,345112,90,우림시장,41,고등어 1마리,NaN,3000,2024-04-01 00:00:00,NaN,2024-04-29 00:00:00,1,전통시장,260000,중랑구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59525,249284,277,양재시장,55,식용유 1.8L,NaN,0,2023-11-01 00:00:00,NaN,2023-11-15 00:00:00,1,전통시장,650000,서초구
59526,249249,277,양재시장,11,딸기 100g,NaN,0,2023-11-01 00:00:00,NaN,2023-11-15 00:00:00,1,전통시장,650000,서초구
59527,249254,277,양재시장,63,만두 1800g,NaN,0,2023-11-01 00:00:00,NaN,2023-11-15 00:00:00,1,전통시장,650000,서초구
59528,249244,277,양재시장,36,닭고기 1kg,NaN,7000,2023-11-01 00:00:00,NaN,2023-11-15 00:00:00,1,전통시장,650000,서초구
59529,249236,277,양재시장,20,고구마 1kg,NaN,0,2023-11-01 00:00:00,NaN,2023-11-15 00:00:00,1,전통시장,650000,서초구

In [4]:
df2

                        강수분석 Unnamed: 1 Unnamed: 2
0                     [검색조건]        NaN        NaN
1                   자료구분 : 일        NaN        NaN
2                  자료형태 : 기본        NaN        NaN
3                 지역/지점 : 서울        NaN        NaN
4     기간 : 20210101~20240515        NaN        NaN
...                      ...        ...        ...
1232     2024-05-10 00:00:00        108        NaN
1233     2024-05-11 00:00:00        108       31.7
1234     2024-05-12 00:00:00        108        NaN
1235     2024-05-13 00:00:00        108        NaN
1236     2024-05-14 00:00:00        108        NaN

[1237 rows x 3 columns]

In [5]:
df3

,자치구별(1),자치구별(2),2021,2021.1,2021.2,2021.3,2021.4
0,자치구별(1),자치구별(2),지역내총생산(당해년가격) (백만원),구성비 (%),인구(추계인구) (명),1인당 지역내총생산 (천원),수준지수(서울특별시=100) (%)
1,서울시,소계,472040199,100,9501528,49680,100
2,서울시,종로구,35719537,7.6,149705,238599,480.27
3,서울시,중구,61342710,13,127427,481395,968.98
4,서울시,용산구,13294640,2.8,225647,58918,118.59
5,서울시,성동구,13999893,3,287580,48682,97.99
6,서울시,광진구,6554954,1.4,349926,18732,37.71
7,서울시,동대문구,7711273,1.6,347913,22164,44.61
8,서울시,중랑구,4860242,1,381449,12742,25.65
9,서울시,성북구,6371894,1.3,436199,14608,29.4
10,서울시,강북구,3462961,0.7,294628,11754,23.66
11,서울시,도봉구,3490683,0.7,310752,11233,22.61
12,서울시,노원구,6728358,1.4,504709,13331,26.83
13,서울시,은평구,5112192,1.1,458946,11139,22.42
14,서울시,서대문구,9039083,1.9,313930,28793,57.96
15,서울시,마포구,21399314,4.5,365136,58606,117.97
16,서울시,양천구,7356067,1.6,435359,16897,34.01
17,서울시,강서구,18347568,3.9,560939,32709,65.84
18,서울시,구로구,14663398,3.1,429461,34144,68.73
19,서울시,금천구,17801015,3.8,248029,71770,144.46
20,서울시,영등포구,44265877,9.4,405738,109100,219.6
21,서울시,동작구,6712864,1.4,389147,17250,34.72
22,서울시,관악구,6347562,1.3,496221,12792,25.75
23,서울시,서초구,38335706,8.1,396100,96783,194.81
24,서울시,강남구,77924019,16.5,501576,155358,312.72
25,서울시,송파구,31834324,6.7,633013,50290,101.23
26,서울시,강동구,9364063,2,451998,20717,41.7